const FlowerData = [
  {
    id: '2f14d1d0-bf82-4bdf-8c79-7dcefd131fa0',
    name: 'Rose',
    species: 'Rosa spp.',
    color: 'Red',
    bloomTime: 'Spring to Summer',
    origin: 'Europe',
    heightInCm: 120,
    widthInCm: 60,
    soilType: 'Loamy',
    sunExposure: 'Full Sun',
    wateringFrequency: 'Regular',
    temperatureTolerance: '10°C to 30°C',
    fragrance: true,
    floweringDuration: '4-6 weeks',
    foliageColor: 'Green',
    plantType: 'Perennial',
    growthRate: 'Moderate',
    toxicity: true,
    use: ['Ornamental', 'Medicinal'],
    pests: ['Aphids', 'Spider Mites'],
    diseases: ['Powdery Mildew', 'Black Spot'],
    propagationMethods: ['Cuttings', 'Grafting'],
    pruningRequirements: 'Prune in early spring to maintain shape',
    plantHardinessZone: '3-9',
    companionPlants: ['Lavender', 'Thyme'],
    maintenanceLevel: 'Medium',
    flowerShape: 'Cup-shaped',
    petalCount: 32,
    preferredpH: 6.5,
    seedType: 'Hardy seeds',
    historicalSignificance: 'Symbol of love in many cultures',
  },
  {
    id: 'a7a7f912-ea3b-47da-953e-0459a40f7021',
    name: 'Sunflower',
    species: 'Helianthus annuus',
    color: 'Yellow',
    bloomTime: 'Summer to Fall',
    origin: 'North America',
    heightInCm: 300,
    widthInCm: 150,
    soilType: 'Sandy',
    sunExposure: 'Full Sun',
    wateringFrequency: 'Moderate',
    temperatureTolerance: '15°C to 35°C',
    fragrance: false,
    floweringDuration: '2-3 weeks',
    foliageColor: 'Green',
    plantType: 'Annual',
    growthRate: 'Fast',
    toxicity: false,
    use: ['Ornamental', 'Edible', 'Oil'],
    pests: ['Aphids', 'Beetles'],
    diseases: ['Downy Mildew', 'Rust'],
    propagationMethods: ['Seeds'],
    pruningRequirements: 'No pruning required',
    plantHardinessZone: '4-9',
    companionPlants: ['Corn', 'Beans'],
    maintenanceLevel: 'Low',
    flowerShape: 'Large round disc',
    petalCount: 30,
    preferredpH: 6.0,
    seedType: 'Edible seeds',
    historicalSignificance: 'Used as a symbol of happiness',
  },
  {
    id: 'c7d5a627-5f6b-46d2-9d2d-c8dfe97e4db0',
    name: 'Tulip',
    species: 'Tulipa spp.',
    color: 'Pink',
    bloomTime: 'Spring',
    origin: 'Turkey',
    heightInCm: 40,
    widthInCm: 20,
    soilType: 'Well-drained',
    sunExposure: 'Full Sun',
    wateringFrequency: 'Light',
    temperatureTolerance: '5°C to 20°C',
    fragrance: true,
    floweringDuration: '2-3 weeks',
    foliageColor: 'Green',
    plantType: 'Perennial',
    growthRate: 'Moderate',
    toxicity: false,
    use: ['Ornamental'],
    pests: ['Aphids', 'Snails'],
    diseases: ['Botrytis Blight'],
    propagationMethods: ['Bulbs'],
    pruningRequirements: 'Remove spent flowers to promote bulb growth',
    plantHardinessZone: '3-7',
    companionPlants: ['Hyacinth', 'Daffodil'],
    maintenanceLevel: 'Medium',
    flowerShape: 'Cup-shaped',
    petalCount: 6,
    preferredpH: 6.5,
    seedType: 'Non-edible',
    historicalSignificance: 'Popular in Dutch culture and art',
  },

  {
    id: '35e74ed6-8b5f-4a73-9d01-bf577bda2560',
    name: 'Lily',
    species: 'Lilium spp.',
    color: 'White',
    bloomTime: 'Summer',
    origin: 'Asia',
    heightInCm: 100,
    widthInCm: 50,
    soilType: 'Rich, well-drained',
    sunExposure: 'Full Sun',
    wateringFrequency: 'Moderate',
    temperatureTolerance: '10°C to 25°C',
    fragrance: true,
    floweringDuration: '4-6 weeks',
    foliageColor: 'Dark Green',
    plantType: 'Perennial',
    growthRate: 'Moderate',
    toxicity: true,
    use: ['Ornamental'],
    pests: ['Lily Beetles', 'Aphids'],
    diseases: ['Lily Mosaic Virus'],
    propagationMethods: ['Bulbs'],
    pruningRequirements: 'Prune spent flowers to encourage more blooms',
    plantHardinessZone: '4-9',
    companionPlants: ['Lavender', 'Daylilies'],
    maintenanceLevel: 'Medium',
    flowerShape: 'Trumpet-shaped',
    petalCount: 6,
    preferredpH: 6.5,
    seedType: 'Non-edible',
    historicalSignificance: 'Symbol of purity in many cultures',
  },
  {
    id: '9812b22e-b2c0-402d-8b35-736fd3925e0b',
    name: 'Daffodil',
    species: 'Narcissus spp.',
    color: 'Yellow',
    bloomTime: 'Spring',
    origin: 'Europe',
    heightInCm: 35,
    widthInCm: 15,
    soilType: 'Well-drained, moderately fertile',
    sunExposure: 'Full Sun to Partial Shade',
    wateringFrequency: 'Moderate',
    temperatureTolerance: '5°C to 15°C',
    fragrance: true,
    floweringDuration: '3-4 weeks',
    foliageColor: 'Green',
    plantType: 'Perennial',
    growthRate: 'Slow',
    toxicity: true,
    use: ['Ornamental'],
    pests: ['Snails', 'Slugs'],
    diseases: ['Basal Rot'],
    propagationMethods: ['Bulbs'],
    pruningRequirements: 'Remove dead flowers after blooming',
    plantHardinessZone: '3-8',
    companionPlants: ['Crocus', 'Hyacinth'],
    maintenanceLevel: 'Low',
    flowerShape: 'Cup-shaped with trumpet',
    petalCount: 6,
    preferredpH: 6.0,
    seedType: 'Non-edible',
    historicalSignificance: 'Associated with spring and renewal',
  },
  {
    id: 'abe78ad4-3a6d-46d8-93fe-890a3ad5f460',
    name: 'Chrysanthemum',
    species: 'Chrysanthemum morifolium',
    color: 'Purple',
    bloomTime: 'Autumn',
    origin: 'China',
    heightInCm: 70,
    widthInCm: 50,
    soilType: 'Loamy',
    sunExposure: 'Full Sun',
    wateringFrequency: 'Moderate',
    temperatureTolerance: '10°C to 20°C',
    fragrance: false,
    floweringDuration: '4-6 weeks',
    foliageColor: 'Green',
    plantType: 'Perennial',
    growthRate: 'Fast',
    toxicity: false,
    use: ['Ornamental'],
    pests: ['Aphids', 'Whiteflies'],
    diseases: ['Powdery Mildew'],
    propagationMethods: ['Cuttings', 'Division'],
    pruningRequirements: 'Prune back after blooming to maintain shape',
    plantHardinessZone: '5-9',
    companionPlants: ['Zinnias', 'Marigolds'],
    maintenanceLevel: 'Medium',
    flowerShape: 'Flat, daisy-like',
    petalCount: 30,
    preferredpH: 6.5,
    seedType: 'Non-edible',
    historicalSignificance: 'Symbol of longevity and happiness in Japan',
  },
  {
    id: 'a8d0f1a4-cc1b-4069-8b2a-cb179f9fe377',
    name: 'Iris',
    species: 'Iris germanica',
    color: 'Blue',
    bloomTime: 'Spring',
    origin: 'Europe',
    heightInCm: 80,
    widthInCm: 40,
    soilType: 'Well-drained',
    sunExposure: 'Full Sun',
    wateringFrequency: 'Light',
    temperatureTolerance: '10°C to 25°C',
    fragrance: false,
    floweringDuration: '3-4 weeks',
    foliageColor: 'Green',
    plantType: 'Perennial',
    growthRate: 'Moderate',
    toxicity: true,
    use: ['Ornamental'],
    pests: ['Aphids', 'Beetles'],
    diseases: ['Leaf Spot', 'Rot'],
    propagationMethods: ['Rhizomes'],
    pruningRequirements: 'Remove dead flowers to encourage more blooms',
    plantHardinessZone: '3-9',
    companionPlants: ['Lavender', 'Daylilies'],
    maintenanceLevel: 'Medium',
    flowerShape: 'Funnel-shaped',
    petalCount: 6,
    preferredpH: 6.0,
    seedType: 'Non-edible',
    historicalSignificance: 'Symbol of wisdom and courage',
  },
  {
    id: 'bbf2e2b1-bc0f-4374-a87a-b2d019fad378',
    name: 'Orchid',
    species: 'Orchidaceae spp.',
    color: 'Pink',
    bloomTime: 'Year-round',
    origin: 'Tropical Asia',
    heightInCm: 50,
    widthInCm: 25,
    soilType: 'Well-drained, slightly acidic',
    sunExposure: 'Indirect Sun',
    wateringFrequency: 'Low',
    temperatureTolerance: '15°C to 25°C',
    fragrance: true,
    floweringDuration: '2-3 months',
    foliageColor: 'Green',
    plantType: 'Perennial',
    growthRate: 'Slow',
    toxicity: true,
    use: ['Ornamental', 'Medicinal'],
    pests: ['Mealybugs', 'Scale Insects'],
    diseases: ['Root Rot'],
    propagationMethods: ['Division', 'Seeds'],
    pruningRequirements: 'Remove dead flowers and leaves',
    plantHardinessZone: '10-11',
    companionPlants: ['Ferns', 'Bromeliads'],
    maintenanceLevel: 'High',
    flowerShape: 'Dainty, symmetrical',
    petalCount: 5,
    preferredpH: 6.0,
    seedType: 'Non-edible',
    historicalSignificance: 'Symbol of beauty and luxury',
  },

  {
    id: '35e74ed6-8b5f-4a73-9d01-bf577bda2560',
    name: 'Lily',
    species: 'Lilium spp.',
    color: 'White',
    bloomTime: 'Summer',
    origin: 'Asia',
    heightInCm: 100,
    widthInCm: 50,
    soilType: 'Rich, well-drained',
    sunExposure: 'Full Sun',
    wateringFrequency: 'Moderate',
    temperatureTolerance: '10°C to 25°C',
    fragrance: true,
    floweringDuration: '4-6 weeks',
    foliageColor: 'Dark Green',
    plantType: 'Perennial',
    growthRate: 'Moderate',
    toxicity: true,
    use: ['Ornamental'],
    pests: ['Lily Beetles', 'Aphids'],
    diseases: ['Lily Mosaic Virus'],
    propagationMethods: ['Bulbs'],
    pruningRequirements: 'Prune spent flowers to encourage more blooms',
    plantHardinessZone: '4-9',
    companionPlants: ['Lavender', 'Daylilies'],
    maintenanceLevel: 'Medium',
    flowerShape: 'Trumpet-shaped',
    petalCount: 6,
    preferredpH: 6.5,
    seedType: 'Non-edible',
    historicalSignificance: 'Symbol of purity in many cultures',
  },
  {
    id: '9812b22e-b2c0-402d-8b35-736fd3925e0b',
    name: 'Daffodil',
    species: 'Narcissus spp.',
    color: 'Yellow',
    bloomTime: 'Spring',
    origin: 'Europe',
    heightInCm: 35,
    widthInCm: 15,
    soilType: 'Well-drained, moderately fertile',
    sunExposure: 'Full Sun to Partial Shade',
    wateringFrequency: 'Moderate',
    temperatureTolerance: '5°C to 15°C',
    fragrance: true,
    floweringDuration: '3-4 weeks',
    foliageColor: 'Green',
    plantType: 'Perennial',
    growthRate: 'Slow',
    toxicity: true,
    use: ['Ornamental'],
    pests: ['Snails', 'Slugs'],
    diseases: ['Basal Rot'],
    propagationMethods: ['Bulbs'],
    pruningRequirements: 'Remove dead flowers after blooming',
    plantHardinessZone: '3-8',
    companionPlants: ['Crocus', 'Hyacinth'],
    maintenanceLevel: 'Low',
    flowerShape: 'Cup-shaped with trumpet',
    petalCount: 6,
    preferredpH: 6.0,
    seedType: 'Non-edible',
    historicalSignificance: 'Associated with spring and renewal',
  },
  {
    id: 'abe78ad4-3a6d-46d8-93fe-890a3ad5f460',
    name: 'Chrysanthemum',
    species: 'Chrysanthemum morifolium',
    color: 'Purple',
    bloomTime: 'Autumn',
    origin: 'China',
    heightInCm: 70,
    widthInCm: 50,
    soilType: 'Loamy',
    sunExposure: 'Full Sun',
    wateringFrequency: 'Moderate',
    temperatureTolerance: '10°C to 20°C',
    fragrance: false,
    floweringDuration: '4-6 weeks',
    foliageColor: 'Green',
    plantType: 'Perennial',
    growthRate: 'Fast',
    toxicity: false,
    use: ['Ornamental'],
    pests: ['Aphids', 'Whiteflies'],
    diseases: ['Powdery Mildew'],
    propagationMethods: ['Cuttings', 'Division'],
    pruningRequirements: 'Prune back after blooming to maintain shape',
    plantHardinessZone: '5-9',
    companionPlants: ['Zinnias', 'Marigolds'],
    maintenanceLevel: 'Medium',
    flowerShape: 'Flat, daisy-like',
    petalCount: 30,
    preferredpH: 6.5,
    seedType: 'Non-edible',
    historicalSignificance: 'Symbol of longevity and happiness in Japan',
  },
  {
    id: 'a8d0f1a4-cc1b-4069-8b2a-cb179f9fe377',
    name: 'Iris',
    species: 'Iris germanica',
    color: 'Blue',
    bloomTime: 'Spring',
    origin: 'Europe',
    heightInCm: 80,
    widthInCm: 40,
    soilType: 'Well-drained',
    sunExposure: 'Full Sun',
    wateringFrequency: 'Light',
    temperatureTolerance: '10°C to 25°C',
    fragrance: false,
    floweringDuration: '3-4 weeks',
    foliageColor: 'Green',
    plantType: 'Perennial',
    growthRate: 'Moderate',
    toxicity: true,
    use: ['Ornamental'],
    pests: ['Aphids', 'Beetles'],
    diseases: ['Leaf Spot', 'Rot'],
    propagationMethods: ['Rhizomes'],
    pruningRequirements: 'Remove dead flowers to encourage more blooms',
    plantHardinessZone: '3-9',
    companionPlants: ['Lavender', 'Daylilies'],
    maintenanceLevel: 'Medium',
    flowerShape: 'Funnel-shaped',
    petalCount: 6,
    preferredpH: 6.0,
    seedType: 'Non-edible',
    historicalSignificance: 'Symbol of wisdom and courage',
  },
  {
    id: 'bbf2e2b1-bc0f-4374-a87a-b2d019fad378',
    name: 'Orchid',
    species: 'Orchidaceae spp.',
    color: 'Pink',
    bloomTime: 'Year-round',
    origin: 'Tropical Asia',
    heightInCm: 50,
    widthInCm: 25,
    soilType: 'Well-drained, slightly acidic',
    sunExposure: 'Indirect Sun',
    wateringFrequency: 'Low',
    temperatureTolerance: '15°C to 25°C',
    fragrance: true,
    floweringDuration: '2-3 months',
    foliageColor: 'Green',
    plantType: 'Perennial',
    growthRate: 'Slow',
    toxicity: true,
    use: ['Ornamental', 'Medicinal'],
    pests: ['Mealybugs', 'Scale Insects'],
    diseases: ['Root Rot'],
    propagationMethods: ['Division', 'Seeds'],
    pruningRequirements: 'Remove dead flowers and leaves',
    plantHardinessZone: '10-11',
    companionPlants: ['Ferns', 'Bromeliads'],
    maintenanceLevel: 'High',
    flowerShape: 'Dainty, symmetrical',
    petalCount: 5,
    preferredpH: 6.0,
    seedType: 'Non-edible',
    historicalSignificance: 'Symbol of beauty and luxury',
  },
  {
    id: 'b47d7277-e3e9-4192-9232-0306580a3ad6',
    name: 'Lavender',
    species: 'Lavandula angustifolia',
    color: 'Purple',
    bloomTime: 'Summer',
    origin: 'Mediterranean',
    heightInCm: 60,
    widthInCm: 40,
    soilType: 'Well-drained, sandy',
    sunExposure: 'Full Sun',
    wateringFrequency: 'Low',
    temperatureTolerance: '5°C to 30°C',
    fragrance: true,
    floweringDuration: '2-4 weeks',
    foliageColor: 'Silver-green',
    plantType: 'Perennial',
    growthRate: 'Slow',
    toxicity: false,
    use: ['Ornamental', 'Aromatherapy', 'Culinary'],
    pests: ['Aphids', 'Whiteflies'],
    diseases: ['Root Rot'],
    propagationMethods: ['Cuttings', 'Seeds'],
    pruningRequirements: 'Prune in early spring to promote growth',
    plantHardinessZone: '5-9',
    companionPlants: ['Rosemary', 'Sage'],
    maintenanceLevel: 'Low',
    flowerShape: 'Spike-like',
    petalCount: 10,
    preferredpH: 6.5,
    seedType: 'Non-edible',
    historicalSignificance: 'Used in perfumes and essential oils for centuries',
  },
  {
    id: '42cb1e8c-df45-4d99-8bde-32c4e1c35c36',
    name: 'Peony',
    species: 'Paeonia spp.',
    color: 'Pink',
    bloomTime: 'Spring to Early Summer',
    origin: 'Asia',
    heightInCm: 80,
    widthInCm: 60,
    soilType: 'Loamy, rich',
    sunExposure: 'Full Sun to Partial Shade',
    wateringFrequency: 'Moderate',
    temperatureTolerance: '5°C to 20°C',
    fragrance: true,
    floweringDuration: '3-4 weeks',
    foliageColor: 'Green',
    plantType: 'Perennial',
    growthRate: 'Moderate',
    toxicity: false,
    use: ['Ornamental'],
    pests: ['Aphids', 'Ants'],
    diseases: ['Botrytis Blight'],
    propagationMethods: ['Division', 'Seeds'],
    pruningRequirements: 'Cut back after flowering to encourage new shoots',
    plantHardinessZone: '3-8',
    companionPlants: ['Hostas', 'Salvia'],
    maintenanceLevel: 'Medium',
    flowerShape: 'Large, rounded',
    petalCount: 30,
    preferredpH: 6.5,
    seedType: 'Non-edible',
    historicalSignificance: 'Symbol of prosperity and good fortune in China',
  },
  {
    id: '5f342d80-6ea7-49a0-a22d-42baf92d0d84',
    name: 'Tulip',
    species: 'Tulipa spp.',
    color: 'Red',
    bloomTime: 'Spring',
    origin: 'Turkey',
    heightInCm: 35,
    widthInCm: 15,
    soilType: 'Well-drained, fertile',
    sunExposure: 'Full Sun',
    wateringFrequency: 'Moderate',
    temperatureTolerance: '10°C to 20°C',
    fragrance: false,
    floweringDuration: '2-3 weeks',
    foliageColor: 'Green',
    plantType: 'Perennial',
    growthRate: 'Moderate',
    toxicity: true,
    use: ['Ornamental'],
    pests: ['Aphids', 'Snails'],
    diseases: ['Botrytis Blight'],
    propagationMethods: ['Bulbs'],
    pruningRequirements: 'Remove spent flowers to encourage more blooms',
    plantHardinessZone: '3-7',
    companionPlants: ['Hyacinths', 'Daffodils'],
    maintenanceLevel: 'Medium',
    flowerShape: 'Cup-shaped',
    petalCount: 6,
    preferredpH: 6.0,
    seedType: 'Non-edible',
    historicalSignificance: 'Symbol of perfect love',
  },
  {
    id: '028dbfd3-39c7-47d7-b951-d3d4405fd818',
    name: 'Violet',
    species: 'Viola spp.',
    color: 'Purple',
    bloomTime: 'Spring',
    origin: 'Europe',
    heightInCm: 25,
    widthInCm: 20,
    soilType: 'Moist, well-drained',
    sunExposure: 'Partial Shade',
    wateringFrequency: 'Regular',
    temperatureTolerance: '5°C to 15°C',
    fragrance: true,
    floweringDuration: '3-4 weeks',
    foliageColor: 'Green',
    plantType: 'Perennial',
    growthRate: 'Slow',
    toxicity: false,
    use: ['Ornamental', 'Culinary'],
    pests: ['Aphids', 'Slugs'],
    diseases: ['Downy Mildew'],
    propagationMethods: ['Seeds', 'Division'],
    pruningRequirements: 'Prune back after blooming to maintain shape',
    plantHardinessZone: '4-9',
    companionPlants: ['Primroses', 'Lobelia'],
    maintenanceLevel: 'Low',
    flowerShape: 'Heart-shaped petals',
    petalCount: 5,
    preferredpH: 6.5,
    seedType: 'Non-edible',
    historicalSignificance: 'Symbol of modesty and loyalty',
  },
  {
    id: 'f5db22b3-c93a-406f-b4b5-bdc98d05efb3',
    name: 'Begonia',
    species: 'Begonia spp.',
    color: 'Red',
    bloomTime: 'Spring to Fall',
    origin: 'Tropical and subtropical regions',
    heightInCm: 30,
    widthInCm: 40,
    soilType: 'Rich, well-drained',
    sunExposure: 'Partial Shade',
    wateringFrequency: 'Moderate',
    temperatureTolerance: '15°C to 25°C',
    fragrance: false,
    floweringDuration: '2-3 weeks',
    foliageColor: 'Green with red veins',
    plantType: 'Perennial',
    growthRate: 'Moderate',
    toxicity: false,
    use: ['Ornamental'],
    pests: ['Aphids', 'Whiteflies'],
    diseases: ['Powdery Mildew'],
    propagationMethods: ['Cuttings'],
    pruningRequirements: 'Prune to remove dead flowers',
    plantHardinessZone: '9-11',
    companionPlants: ['Coleus', 'Impatiens'],
    maintenanceLevel: 'Medium',
    flowerShape: 'Symmetrical, rounded',
    petalCount: 5,
    preferredpH: 6.0,
    seedType: 'Non-edible',
    historicalSignificance: 'Popular in Victorian gardens',
  },
  {
    id: 'cb33b156-2150-43ba-bf96-0e91d8bc8c82',
    name: 'Snapdragon',
    species: 'Antirrhinum majus',
    color: 'Orange',
    bloomTime: 'Spring to Summer',
    origin: 'Mediterranean',
    heightInCm: 60,
    widthInCm: 25,
    soilType: 'Loamy, well-drained',
    sunExposure: 'Full Sun to Partial Shade',
    wateringFrequency: 'Moderate',
    temperatureTolerance: '10°C to 25°C',
    fragrance: false,
    floweringDuration: '4-6 weeks',
    foliageColor: 'Green',
    plantType: 'Biennial',
    growthRate: 'Moderate',
    toxicity: false,
    use: ['Ornamental'],
    pests: ['Aphids', 'Spider Mites'],
    diseases: ['Rust', 'Downy Mildew'],
    propagationMethods: ['Cuttings', 'Seeds'],
    pruningRequirements: 'Cut back to encourage new growth',
    plantHardinessZone: '4-9',
    companionPlants: ['Petunias', 'Marigolds'],
    maintenanceLevel: 'Medium',
    flowerShape: 'Snapdragon-like, tubular',
    petalCount: 5,
    preferredpH: 6.0,
    seedType: 'Non-edible',
    historicalSignificance: 'Symbol of strength and resilience',
  },
  {
    id: '8ba5d027-d77b-44ab-b3ba-d3569b156d70',
    name: 'Camellia',
    species: 'Camellia japonica',
    color: 'White',
    bloomTime: 'Winter to Early Spring',
    origin: 'Asia',
    heightInCm: 150,
    widthInCm: 100,
    soilType: 'Acidic, well-drained',
    sunExposure: 'Partial Shade',
    wateringFrequency: 'Moderate',
    temperatureTolerance: '0°C to 15°C',
    fragrance: true,
    floweringDuration: '6-8 weeks',
    foliageColor: 'Dark Green',
    plantType: 'Evergreen',
    growthRate: 'Slow',
    toxicity: false,
    use: ['Ornamental'],
    pests: ['Spider Mites', 'Mealybugs'],
    diseases: ['Leaf Spot', 'Botrytis Blight'],
    propagationMethods: ['Cuttings', 'Layering'],
    pruningRequirements: 'Prune after blooming to maintain shape',
    plantHardinessZone: '7-9',
    companionPlants: ['Azaleas', 'Ferns'],
    maintenanceLevel: 'High',
    flowerShape: 'Large, rosette',
    petalCount: 5,
    preferredpH: 5.5,
    seedType: 'Non-edible',
    historicalSignificance: 'Symbol of perfection in Japanese culture',
  },
  {
    id: '63cc9c6e-51c1-4be9-8f09-5da3d2cce7e9',
    name: 'Geranium',
    species: 'Pelargonium spp.',
    color: 'Pink',
    bloomTime: 'Summer',
    origin: 'South Africa',
    heightInCm: 40,
    widthInCm: 35,
    soilType: 'Well-drained, loamy',
    sunExposure: 'Full Sun',
    wateringFrequency: 'Moderate',
    temperatureTolerance: '10°C to 30°C',
    fragrance: false,
    floweringDuration: '4-6 weeks',
    foliageColor: 'Green',
    plantType: 'Perennial',
    growthRate: 'Moderate',
    toxicity: false,
    use: ['Ornamental'],
    pests: ['Aphids', 'Whiteflies'],
    diseases: ['Powdery Mildew'],
    propagationMethods: ['Cuttings'],
    pruningRequirements: 'Cut back after flowering',
    plantHardinessZone: '9-11',
    companionPlants: ['Petunias', 'Fuchsias'],
    maintenanceLevel: 'Medium',
    flowerShape: 'Rounded, five-petaled',
    petalCount: 5,
    preferredpH: 6.5,
    seedType: 'Non-edible',
    historicalSignificance: 'A symbol of Geranium family',
  },
  {
    id: 'ddc7b410-79b2-4475-bc5c-3728ef7e44a1',
    name: 'Zinnia',
    species: 'Zinnia elegans',
    color: 'Orange',
    bloomTime: 'Summer to Fall',
    origin: 'Mexico',
    heightInCm: 60,
    widthInCm: 40,
    soilType: 'Well-drained, sandy',
    sunExposure: 'Full Sun',
    wateringFrequency: 'Moderate',
    temperatureTolerance: '15°C to 30°C',
    fragrance: false,
    floweringDuration: '4-6 weeks',
    foliageColor: 'Green',
    plantType: 'Annual',
    growthRate: 'Fast',
    toxicity: false,
    use: ['Ornamental'],
    pests: ['Aphids', 'Caterpillars'],
    diseases: ['Powdery Mildew'],
    propagationMethods: ['Seeds'],
    pruningRequirements: 'Pinch back to encourage bushy growth',
    plantHardinessZone: '3-10',
    companionPlants: ['Marigolds', 'Cosmos'],
    maintenanceLevel: 'Low',
    flowerShape: 'Daisy-like',
    petalCount: 15,
    preferredpH: 6.0,
    seedType: 'Non-edible',
    historicalSignificance: 'Symbol of lasting affection',
  },

  {
    id: '6f720f79-d2fd-4b96-b4c7-7d39b4a24b78',
    name: 'Daffodil',
    species: 'Narcissus spp.',
    color: 'Yellow',
    bloomTime: 'Spring',
    origin: 'Europe, North Africa',
    heightInCm: 35,
    widthInCm: 20,
    soilType: 'Well-drained, sandy',
    sunExposure: 'Full Sun to Partial Shade',
    wateringFrequency: 'Moderate',
    temperatureTolerance: '5°C to 15°C',
    fragrance: true,
    floweringDuration: '2-3 weeks',
    foliageColor: 'Green',
    plantType: 'Perennial',
    growthRate: 'Slow',
    toxicity: true,
    use: ['Ornamental'],
    pests: ['Aphids', 'Snails'],
    diseases: ['Fungal Blight'],
    propagationMethods: ['Bulbs'],
    pruningRequirements: 'Cut back after flowering',
    plantHardinessZone: '4-8',
    companionPlants: ['Tulips', 'Crocus'],
    maintenanceLevel: 'Low',
    flowerShape: 'Trumpet-shaped',
    petalCount: 6,
    preferredpH: 6.0,
    seedType: 'Non-edible',
    historicalSignificance: 'Symbol of renewal and new beginnings',
  },
  {
    id: 'd10f4b02-3e70-4044-b67a-3c3bdeedb19c',
    name: 'Sunflower',
    species: 'Helianthus annuus',
    color: 'Yellow',
    bloomTime: 'Summer',
    origin: 'North America',
    heightInCm: 250,
    widthInCm: 70,
    soilType: 'Loamy, well-drained',
    sunExposure: 'Full Sun',
    wateringFrequency: 'High',
    temperatureTolerance: '15°C to 35°C',
    fragrance: false,
    floweringDuration: '6-8 weeks',
    foliageColor: 'Green',
    plantType: 'Annual',
    growthRate: 'Fast',
    toxicity: false,
    use: ['Ornamental', 'Edible'],
    pests: ['Aphids', 'Birds'],
    diseases: ['Powdery Mildew'],
    propagationMethods: ['Seeds'],
    pruningRequirements: 'Remove spent flowers to prevent self-seeding',
    plantHardinessZone: '3-9',
    companionPlants: ['Corn', 'Beans'],
    maintenanceLevel: 'Low',
    flowerShape: 'Large, round',
    petalCount: 15 - 20,
    preferredpH: 6.0,
    seedType: 'Edible',
    historicalSignificance: 'Symbol of loyalty and adoration',
  },
  {
    id: 'c3e24e7c-bdb6-4a3b-91b1-cedf66e7e22c',
    name: 'Chrysanthemum',
    species: 'Chrysanthemum morifolium',
    color: 'White',
    bloomTime: 'Fall',
    origin: 'Asia',
    heightInCm: 80,
    widthInCm: 50,
    soilType: 'Well-drained, fertile',
    sunExposure: 'Full Sun',
    wateringFrequency: 'Moderate',
    temperatureTolerance: '5°C to 15°C',
    fragrance: true,
    floweringDuration: '4-6 weeks',
    foliageColor: 'Green',
    plantType: 'Perennial',
    growthRate: 'Moderate',
    toxicity: false,
    use: ['Ornamental', 'Medicinal'],
    pests: ['Aphids', 'Spider Mites'],
    diseases: ['Botrytis Blight'],
    propagationMethods: ['Cuttings', 'Division'],
    pruningRequirements: 'Deadhead regularly to extend bloom time',
    plantHardinessZone: '5-9',
    companionPlants: ['Lavender', 'Marigold'],
    maintenanceLevel: 'Medium',
    flowerShape: 'Round, multi-petaled',
    petalCount: 30,
    preferredpH: 6.5,
    seedType: 'Non-edible',
    historicalSignificance: 'Symbol of longevity and happiness in China',
  },
  {
    id: 'ea5502f2-53c1-4199-a5c9-9db6c4d97f2d',
    name: 'Canna Lily',
    species: 'Canna indica',
    color: 'Red',
    bloomTime: 'Summer to Fall',
    origin: 'South America',
    heightInCm: 120,
    widthInCm: 80,
    soilType: 'Moist, well-drained',
    sunExposure: 'Full Sun',
    wateringFrequency: 'High',
    temperatureTolerance: '20°C to 35°C',
    fragrance: false,
    floweringDuration: '8-10 weeks',
    foliageColor: 'Green with red veins',
    plantType: 'Perennial',
    growthRate: 'Fast',
    toxicity: false,
    use: ['Ornamental'],
    pests: ['Aphids', 'Slugs'],
    diseases: ['Leaf Spot'],
    propagationMethods: ['Rhizomes'],
    pruningRequirements: 'Remove spent flowers regularly',
    plantHardinessZone: '7-11',
    companionPlants: ['Fuchsias', 'Impatiens'],
    maintenanceLevel: 'Medium',
    flowerShape: 'Tubular',
    petalCount: 6,
    preferredpH: 6.5,
    seedType: 'Non-edible',
    historicalSignificance: 'Used in tropical gardens for vibrant color',
  },
  {
    id: 'b477f1c2-cd4a-4675-9f1c-bf4d83231c77',
    name: 'Gerbera Daisy',
    species: 'Gerbera jamesonii',
    color: 'Pink',
    bloomTime: 'Spring to Summer',
    origin: 'South Africa',
    heightInCm: 40,
    widthInCm: 30,
    soilType: 'Well-drained, loamy',
    sunExposure: 'Full Sun',
    wateringFrequency: 'Moderate',
    temperatureTolerance: '15°C to 30°C',
    fragrance: false,
    floweringDuration: '6-8 weeks',
    foliageColor: 'Green',
    plantType: 'Perennial',
    growthRate: 'Moderate',
    toxicity: false,
    use: ['Ornamental'],
    pests: ['Aphids', 'Thrips'],
    diseases: ['Powdery Mildew'],
    propagationMethods: ['Cuttings'],
    pruningRequirements: 'Remove dead flowers to encourage blooming',
    plantHardinessZone: '9-11',
    companionPlants: ['Petunias', 'Lobelia'],
    maintenanceLevel: 'Medium',
    flowerShape: 'Daisy-like',
    petalCount: 20,
    preferredpH: 6.5,
    seedType: 'Non-edible',
    historicalSignificance: 'A symbol of cheerfulness',
  },
  {
    id: '9e79d1d0-7552-46a1-8a96-3d40b86424e4',
    name: 'Aster',
    species: 'Aster spp.',
    color: 'Purple',
    bloomTime: 'Fall',
    origin: 'North America, Europe',
    heightInCm: 90,
    widthInCm: 50,
    soilType: 'Well-drained, fertile',
    sunExposure: 'Full Sun',
    wateringFrequency: 'Moderate',
    temperatureTolerance: '10°C to 25°C',
    fragrance: false,
    floweringDuration: '4-6 weeks',
    foliageColor: 'Green',
    plantType: 'Perennial',
    growthRate: 'Moderate',
    toxicity: false,
    use: ['Ornamental'],
    pests: ['Aphids', 'Japanese Beetles'],
    diseases: ['Powdery Mildew', 'Root Rot'],
    propagationMethods: ['Division', 'Cuttings'],
    pruningRequirements: 'Cut back after flowering to prevent re-seeding',
    plantHardinessZone: '4-8',
    companionPlants: ['Rudbeckia', 'Goldenrod'],
    maintenanceLevel: 'Medium',
    flowerShape: 'Daisy-like',
    petalCount: 20 - 30,
    preferredpH: 6.0,
    seedType: 'Non-edible',
    historicalSignificance: 'Symbol of patience and elegance',
  },
  {
    id: 'a7cda3a8-d443-49cc-946f-973d1e0ac6bc',
    name: 'Lilac',
    species: 'Syringa vulgaris',
    color: 'Purple',
    bloomTime: 'Spring',
    origin: 'Europe, Asia',
    heightInCm: 300,
    widthInCm: 250,
    soilType: 'Well-drained, slightly alkaline',
    sunExposure: 'Full Sun',
    wateringFrequency: 'Moderate',
    temperatureTolerance: '-10°C to 25°C',
    fragrance: true,
    floweringDuration: '2-3 weeks',
    foliageColor: 'Green',
    plantType: 'Deciduous',
    growthRate: 'Moderate',
    toxicity: false,
    use: ['Ornamental'],
    pests: ['Aphids', 'Scale Insects'],
    diseases: ['Powdery Mildew'],
    propagationMethods: ['Cuttings'],
    pruningRequirements: 'Prune after flowering to maintain shape',
    plantHardinessZone: '3-7',
    companionPlants: ['Hostas', 'Peonies'],
    maintenanceLevel: 'Medium',
    flowerShape: 'Panicle',
    petalCount: 4,
    preferredpH: 7.0,
    seedType: 'Non-edible',
    historicalSignificance: 'Symbol of love and first love',
  },
  {
    id: '4a3f5e5e-4e58-4ef9-90cd-595bc6d6a4c5',
    name: 'Peony',
    species: 'Paeonia spp.',
    color: 'Pink',
    bloomTime: 'Spring to Early Summer',
    origin: 'Europe, Asia',
    heightInCm: 80,
    widthInCm: 70,
    soilType: 'Well-drained, fertile',
    sunExposure: 'Full Sun',
    wateringFrequency: 'Moderate',
    temperatureTolerance: '5°C to 20°C',
    fragrance: true,
    floweringDuration: '2-4 weeks',
    foliageColor: 'Green',
    plantType: 'Perennial',
    growthRate: 'Moderate',
    toxicity: false,
    use: ['Ornamental', 'Medicinal'],
    pests: ['Aphids', 'Caterpillars'],
    diseases: ['Botrytis Blight'],
    propagationMethods: ['Division', 'Seeds'],
    pruningRequirements: 'Cut back after flowering to maintain shape',
    plantHardinessZone: '3-8',
    companionPlants: ['Irises', 'Astilbes'],
    maintenanceLevel: 'Medium',
    flowerShape: 'Large, round',
    petalCount: 10 - 20,
    preferredpH: 6.5,
    seedType: 'Non-edible',
    historicalSignificance:
      'Symbol of wealth, good fortune, and happy marriage',
  },

  {
    id: 'f93ac0d7-ec9c-43b2-b539-6fa24b505d61',
    name: 'Orchid',
    species: 'Phalaenopsis spp.',
    color: 'Purple',
    bloomTime: 'Year-round',
    origin: 'Southeast Asia',
    heightInCm: 50,
    widthInCm: 30,
    soilType: 'Well-drained, orchid mix',
    sunExposure: 'Partial Shade',
    wateringFrequency: 'Low',
    temperatureTolerance: '18°C to 30°C',
    fragrance: true,
    floweringDuration: '6-8 weeks',
    foliageColor: 'Green',
    plantType: 'Perennial',
    growthRate: 'Slow',
    toxicity: true,
    use: ['Ornamental'],
    pests: ['Mealybugs', 'Scale'],
    diseases: ['Root Rot'],
    propagationMethods: ['Division', 'Keiki'],
    pruningRequirements: 'Cut spent flowers after blooming',
    plantHardinessZone: '10-12',
    companionPlants: ['Ferns', 'Bromeliads'],
    maintenanceLevel: 'Medium',
    flowerShape: 'Flat, asymmetric',
    petalCount: 5,
    preferredpH: 5.5,
    seedType: 'Non-edible',
    historicalSignificance: 'Symbol of luxury and strength',
  },
  {
    id: '4b157b17-8a6e-4c1e-b9ad-d6580a2d4fd3',
    name: 'Lavender',
    species: 'Lavandula angustifolia',
    color: 'Purple',
    bloomTime: 'Summer',
    origin: 'Mediterranean',
    heightInCm: 60,
    widthInCm: 50,
    soilType: 'Well-drained, sandy',
    sunExposure: 'Full Sun',
    wateringFrequency: 'Low',
    temperatureTolerance: '5°C to 30°C',
    fragrance: true,
    floweringDuration: '6-8 weeks',
    foliageColor: 'Gray-green',
    plantType: 'Perennial',
    growthRate: 'Moderate',
    toxicity: false,
    use: ['Ornamental', 'Medicinal', 'Culinary'],
    pests: ['Aphids', 'Whiteflies'],
    diseases: ['Root Rot'],
    propagationMethods: ['Cuttings'],
    pruningRequirements: 'Prune after flowering to encourage new growth',
    plantHardinessZone: '5-9',
    companionPlants: ['Rosemary', 'Thyme'],
    maintenanceLevel: 'Low',
    flowerShape: 'Spike-like',
    petalCount: 4 - 6,
    preferredpH: 6.5,
    seedType: 'Non-edible',
    historicalSignificance: 'Symbol of purity and calm',
  },
  {
    id: '7d4b35de-4283-4c34-9b51-71ea5b7b3c2a',
    name: 'Tulip',
    species: 'Tulipa spp.',
    color: 'Red',
    bloomTime: 'Spring',
    origin: 'Turkey, Central Asia',
    heightInCm: 40,
    widthInCm: 25,
    soilType: 'Well-drained, loamy',
    sunExposure: 'Full Sun',
    wateringFrequency: 'Moderate',
    temperatureTolerance: '5°C to 20°C',
    fragrance: false,
    floweringDuration: '3-4 weeks',
    foliageColor: 'Green',
    plantType: 'Perennial',
    growthRate: 'Moderate',
    toxicity: true,
    use: ['Ornamental'],
    pests: ['Aphids', 'Snails'],
    diseases: ['Tulip Fire', 'Botrytis Blight'],
    propagationMethods: ['Bulbs'],
    pruningRequirements: 'Cut back after blooming',
    plantHardinessZone: '3-8',
    companionPlants: ['Hyacinth', 'Crocus'],
    maintenanceLevel: 'Medium',
    flowerShape: 'Cup-shaped',
    petalCount: 6,
    preferredpH: 6.0,
    seedType: 'Non-edible',
    historicalSignificance: 'Symbol of perfect love',
  },
  {
    id: '3fcbebfd-b72d-4e02-b7b9-f92cc47674b5',
    name: 'Black-eyed Susan',
    species: 'Rudbeckia hirta',
    color: 'Yellow',
    bloomTime: 'Summer to Fall',
    origin: 'North America',
    heightInCm: 90,
    widthInCm: 60,
    soilType: 'Well-drained, loamy',
    sunExposure: 'Full Sun',
    wateringFrequency: 'Moderate',
    temperatureTolerance: '15°C to 30°C',
    fragrance: false,
    floweringDuration: '6-8 weeks',
    foliageColor: 'Green',
    plantType: 'Perennial',
    growthRate: 'Fast',
    toxicity: false,
    use: ['Ornamental'],
    pests: ['Aphids', 'Caterpillars'],
    diseases: ['Powdery Mildew'],
    propagationMethods: ['Seeds', 'Division'],
    pruningRequirements: 'Remove dead flowers to promote new blooms',
    plantHardinessZone: '3-9',
    companionPlants: ['Purple Coneflower', 'Salvia'],
    maintenanceLevel: 'Low',
    flowerShape: 'Daisy-like',
    petalCount: 10 - 15,
    preferredpH: 6.0,
    seedType: 'Non-edible',
    historicalSignificance: 'Symbol of encouragement and justice',
  },
  {
    id: 'bde69e82-cf8c-4787-99cb-8a4de98e8e48',
    name: 'Freesia',
    species: 'Freesia spp.',
    color: 'Yellow',
    bloomTime: 'Spring',
    origin: 'South Africa',
    heightInCm: 30,
    widthInCm: 20,
    soilType: 'Well-drained, sandy',
    sunExposure: 'Full Sun',
    wateringFrequency: 'Moderate',
    temperatureTolerance: '10°C to 20°C',
    fragrance: true,
    floweringDuration: '3-4 weeks',
    foliageColor: 'Green',
    plantType: 'Perennial',
    growthRate: 'Moderate',
    toxicity: false,
    use: ['Ornamental', 'Fragrance'],
    pests: ['Aphids', 'Thrips'],
    diseases: ['Botrytis Blight'],
    propagationMethods: ['Bulbs', 'Cuttings'],
    pruningRequirements: 'Deadhead after flowering',
    plantHardinessZone: '7-10',
    companionPlants: ['Crocus', 'Tulips'],
    maintenanceLevel: 'Medium',
    flowerShape: 'Bell-shaped',
    petalCount: 6,
    preferredpH: 6.0,
    seedType: 'Non-edible',
    historicalSignificance: 'Symbol of innocence and sweetness',
  },
  {
    id: 'ea9302e7-bd34-45b4-888f-79ec7e699f96',
    name: 'Hibiscus',
    species: 'Hibiscus rosa-sinensis',
    color: 'Red',
    bloomTime: 'Summer to Fall',
    origin: 'Asia',
    heightInCm: 150,
    widthInCm: 120,
    soilType: 'Well-drained, loamy',
    sunExposure: 'Full Sun',
    wateringFrequency: 'Moderate',
    temperatureTolerance: '15°C to 30°C',
    fragrance: true,
    floweringDuration: '6-8 weeks',
    foliageColor: 'Green',
    plantType: 'Perennial',
    growthRate: 'Moderate',
    toxicity: false,
    use: ['Ornamental', 'Medicinal'],
    pests: ['Aphids', 'Whiteflies'],
    diseases: ['Powdery Mildew'],
    propagationMethods: ['Cuttings'],
    pruningRequirements: 'Prune after blooming to encourage more flowers',
    plantHardinessZone: '9-11',
    companionPlants: ['Bougainvillea', 'Plumbago'],
    maintenanceLevel: 'Medium',
    flowerShape: 'Large, trumpet-shaped',
    petalCount: 5,
    preferredpH: 6.5,
    seedType: 'Non-edible',
    historicalSignificance: 'Symbol of beauty and delicate femininity',
  },
  {
    id: 'c56e233b-6f79-4cf7-9141-b9e3e713f720',
    name: 'Geranium',
    species: 'Pelargonium spp.',
    color: 'Pink',
    bloomTime: 'Spring to Fall',
    origin: 'South Africa',
    heightInCm: 30,
    widthInCm: 30,
    soilType: 'Well-drained, loamy',
    sunExposure: 'Full Sun',
    wateringFrequency: 'Moderate',
    temperatureTolerance: '10°C to 25°C',
    fragrance: true,
    floweringDuration: '4-6 weeks',
    foliageColor: 'Green',
    plantType: 'Annual',
    growthRate: 'Moderate',
    toxicity: false,
    use: ['Ornamental'],
    pests: ['Aphids', 'Spider Mites'],
    diseases: ['Powdery Mildew'],
    propagationMethods: ['Cuttings'],
    pruningRequirements: 'Pinch back to encourage bushy growth',
    plantHardinessZone: '9-11',
    companionPlants: ['Petunias', 'Impatiens'],
    maintenanceLevel: 'Low',
    flowerShape: 'Clustered, rounded',
    petalCount: 5,
    preferredpH: 6.5,
    seedType: 'Non-edible',
    historicalSignificance: 'Symbol of friendship and comfort',
  },
  {
    id: 'ee61b06b-cd9a-4ebd-b914-4e6ebd7f7f7d',
    name: 'Daffodil',
    species: 'Narcissus spp.',
    color: 'Yellow',
    bloomTime: 'Spring',
    origin: 'Europe, North Africa',
    heightInCm: 40,
    widthInCm: 20,
    soilType: 'Well-drained, sandy',
    sunExposure: 'Full Sun',
    wateringFrequency: 'Moderate',
    temperatureTolerance: '5°C to 20°C',
    fragrance: true,
    floweringDuration: '4-6 weeks',
    foliageColor: 'Green',
    plantType: 'Perennial',
    growthRate: 'Moderate',
    toxicity: true,
    use: ['Ornamental'],
    pests: ['Aphids', 'Snails'],
    diseases: ['Botrytis Blight'],
    propagationMethods: ['Bulbs'],
    pruningRequirements: 'Cut back after flowering',
    plantHardinessZone: '4-8',
    companionPlants: ['Tulips', 'Crocus'],
    maintenanceLevel: 'Low',
    flowerShape: 'Trumpet-shaped',
    petalCount: 6,
    preferredpH: 6.0,
    seedType: 'Non-edible',
    historicalSignificance: 'Symbol of new beginnings',
  },
  {
    id: 'acb0f5b9-428e-4f88-b256-56e9b4d6be1c',
    name: 'Lily',
    species: 'Lilium spp.',
    color: 'White',
    bloomTime: 'Summer',
    origin: 'Asia, Europe',
    heightInCm: 90,
    widthInCm: 30,
    soilType: 'Well-drained, loamy',
    sunExposure: 'Full Sun',
    wateringFrequency: 'Moderate',
    temperatureTolerance: '10°C to 30°C',
    fragrance: true,
    floweringDuration: '4-6 weeks',
    foliageColor: 'Green',
    plantType: 'Perennial',
    growthRate: 'Moderate',
    toxicity: true,
    use: ['Ornamental'],
    pests: ['Aphids', 'Lily Beetles'],
    diseases: ['Botrytis Blight', 'Lily Mosaic Virus'],
    propagationMethods: ['Bulbs', 'Seeds'],
    pruningRequirements: 'Deadhead and cut back after flowering',
    plantHardinessZone: '4-9',
    companionPlants: ['Hostas', 'Daylilies'],
    maintenanceLevel: 'Medium',
    flowerShape: 'Trumpet-shaped',
    petalCount: 6,
    preferredpH: 6.5,
    seedType: 'Non-edible',
    historicalSignificance: 'Symbol of purity and transience',
  },
  {
    id: '8f706456-6b8a-4c5a-8be7-72e0c56c4e97',
    name: 'Sunflower',
    species: 'Helianthus annuus',
    color: 'Yellow',
    bloomTime: 'Summer to Fall',
    origin: 'North America',
    heightInCm: 300,
    widthInCm: 150,
    soilType: 'Well-drained, loamy',
    sunExposure: 'Full Sun',
    wateringFrequency: 'Moderate',
    temperatureTolerance: '10°C to 35°C',
    fragrance: false,
    floweringDuration: '6-8 weeks',
    foliageColor: 'Green',
    plantType: 'Annual',
    growthRate: 'Fast',
    toxicity: false,
    use: ['Ornamental', 'Culinary', 'Oil production'],
    pests: ['Aphids', 'Caterpillars'],
    diseases: ['Downy Mildew', 'Rust'],
    propagationMethods: ['Seeds'],
    pruningRequirements: 'Deadhead to encourage continuous blooming',
    plantHardinessZone: '4-9',
    companionPlants: ['Beans', 'Corn'],
    maintenanceLevel: 'Low',
    flowerShape: 'Daisy-like',
    petalCount: 20 - 30,
    preferredpH: 6.5,
    seedType: 'Edible',
    historicalSignificance: 'Symbol of happiness and vitality',
  },
  {
    id: 'dc597b7e-f6de-4d35-9bb6-3a5c77cfa1e3',
    name: 'Zinnia',
    species: 'Zinnia elegans',
    color: 'Orange',
    bloomTime: 'Summer to Fall',
    origin: 'Mexico',
    heightInCm: 50,
    widthInCm: 40,
    soilType: 'Well-drained, loamy',
    sunExposure: 'Full Sun',
    wateringFrequency: 'Moderate',
    temperatureTolerance: '15°C to 30°C',
    fragrance: false,
    floweringDuration: '8-12 weeks',
    foliageColor: 'Green',
    plantType: 'Annual',
    growthRate: 'Fast',
    toxicity: false,
    use: ['Ornamental'],
    pests: ['Aphids', 'Spider Mites'],
    diseases: ['Powdery Mildew'],
    propagationMethods: ['Seeds'],
    pruningRequirements: 'Deadhead to prolong flowering',
    plantHardinessZone: '3-10',
    companionPlants: ['Marigolds', 'Cosmos'],
    maintenanceLevel: 'Low',
    flowerShape: 'Daisy-like',
    petalCount: 15 - 20,
    preferredpH: 6.5,
    seedType: 'Non-edible',
    historicalSignificance: 'Symbol of endurance and lasting beauty',
  },
  {
    id: 'c4ea95a0-86f0-4376-8cb6-915097b039fc',
    name: 'Camellia',
    species: 'Camellia japonica',
    color: 'Pink',
    bloomTime: 'Winter to Spring',
    origin: 'East Asia',
    heightInCm: 200,
    widthInCm: 150,
    soilType: 'Acidic, well-drained',
    sunExposure: 'Partial Shade',
    wateringFrequency: 'Moderate',
    temperatureTolerance: '5°C to 20°C',
    fragrance: true,
    floweringDuration: '4-6 weeks',
    foliageColor: 'Green',
    plantType: 'Evergreen',
    growthRate: 'Slow',
    toxicity: true,
    use: ['Ornamental'],
    pests: ['Scale Insects', 'Aphids'],
    diseases: ['Petal Blight'],
    propagationMethods: ['Cuttings'],
    pruningRequirements: 'Prune after flowering to shape',
    plantHardinessZone: '7-9',
    companionPlants: ['Azaleas', 'Rhododendrons'],
    maintenanceLevel: 'Medium',
    flowerShape: 'Round, multi-petaled',
    petalCount: 20 - 25,
    preferredpH: 5.5,
    seedType: 'Non-edible',
    historicalSignificance: 'Symbol of love, beauty, and devotion',
  },
  {
    id: '4f02ec7b-5321-4421-8ef1-63c0225e0e2e',
    name: 'Dahlia',
    species: 'Dahlia pinnata',
    color: 'Red',
    bloomTime: 'Summer to Fall',
    origin: 'Mexico',
    heightInCm: 120,
    widthInCm: 90,
    soilType: 'Well-drained, fertile',
    sunExposure: 'Full Sun',
    wateringFrequency: 'Moderate',
    temperatureTolerance: '15°C to 30°C',
    fragrance: false,
    floweringDuration: '6-8 weeks',
    foliageColor: 'Green',
    plantType: 'Perennial',
    growthRate: 'Moderate',
    toxicity: false,
    use: ['Ornamental'],
    pests: ['Aphids', 'Spider Mites'],
    diseases: ['Botrytis Blight', 'Powdery Mildew'],
    propagationMethods: ['Cuttings', 'Division'],
    pruningRequirements: 'Deadhead to encourage new blooms',
    plantHardinessZone: '3-9',
    companionPlants: ['Marigolds', 'Salvia'],
    maintenanceLevel: 'Medium',
    flowerShape: 'Dahlia-like',
    petalCount: 25 - 35,
    preferredpH: 6.0,
    seedType: 'Non-edible',
    historicalSignificance: 'Symbol of strength, elegance, and creativity',
  },
  {
    id: '8e6abbd8-cd95-44a2-85b4-3cdeee36ad50',
    name: 'Snapdragon',
    species: 'Antirrhinum majus',
    color: 'Pink',
    bloomTime: 'Spring to Summer',
    origin: 'Europe, North America',
    heightInCm: 90,
    widthInCm: 40,
    soilType: 'Well-drained, loamy',
    sunExposure: 'Full Sun',
    wateringFrequency: 'Moderate',
    temperatureTolerance: '10°C to 25°C',
    fragrance: false,
    floweringDuration: '8-10 weeks',
    foliageColor: 'Green',
    plantType: 'Annual',
    growthRate: 'Moderate',
    toxicity: false,
    use: ['Ornamental'],
    pests: ['Aphids', 'Whiteflies'],
    diseases: ['Rust'],
    propagationMethods: ['Seeds'],
    pruningRequirements: 'Pinch back to encourage branching',
    plantHardinessZone: '4-10',
    companionPlants: ['Petunias', 'Salvia'],
    maintenanceLevel: 'Low',
    flowerShape: 'Spike-like',
    petalCount: 4 - 5,
    preferredpH: 6.5,
    seedType: 'Non-edible',
    historicalSignificance: 'Symbol of strength and grace',
  },
  {
    id: '4f418e8f-f62f-4c79-92ab-fc6ff520eb5f',
    name: 'Magnolia',
    species: 'Magnolia grandiflora',
    color: 'White',
    bloomTime: 'Spring to Summer',
    origin: 'Eastern United States',
    heightInCm: 150,
    widthInCm: 100,
    soilType: 'Acidic, well-drained',
    sunExposure: 'Full Sun to Partial Shade',
    wateringFrequency: 'Moderate',
    temperatureTolerance: '5°C to 30°C',
    fragrance: true,
    floweringDuration: '4-6 weeks',
    foliageColor: 'Green',
    plantType: 'Evergreen',
    growthRate: 'Moderate',
    toxicity: false,
    use: ['Ornamental'],
    pests: ['Scale Insects', 'Aphids'],
    diseases: ['Powdery Mildew'],
    propagationMethods: ['Cuttings', 'Seeds'],
    pruningRequirements: 'Prune after flowering to shape',
    plantHardinessZone: '7-9',
    companionPlants: ['Azaleas', 'Rhododendrons'],
    maintenanceLevel: 'Medium',
    flowerShape: 'Large, saucer-shaped',
    petalCount: 12 - 15,
    preferredpH: 6.0,
    seedType: 'Non-edible',
    historicalSignificance: 'Symbol of perseverance and dignity',
  },
  {
    id: '23a9267d-3b88-4d94-9746-730b02ec07d9',
    name: 'Lavender',
    species: 'Lavandula angustifolia',
    color: 'Purple',
    bloomTime: 'Summer',
    origin: 'Mediterranean',
    heightInCm: 60,
    widthInCm: 40,
    soilType: 'Well-drained, sandy',
    sunExposure: 'Full Sun',
    wateringFrequency: 'Low',
    temperatureTolerance: '5°C to 30°C',
    fragrance: true,
    floweringDuration: '6-8 weeks',
    foliageColor: 'Green',
    plantType: 'Perennial',
    growthRate: 'Slow',
    toxicity: false,
    use: ['Aromatherapy', 'Ornamental', 'Culinary'],
    pests: ['Aphids', 'Whiteflies'],
    diseases: ['Root Rot'],
    propagationMethods: ['Cuttings', 'Seeds'],
    pruningRequirements: 'Cut back after flowering to maintain shape',
    plantHardinessZone: '5-9',
    companionPlants: ['Rosemary', 'Sage'],
    maintenanceLevel: 'Low',
    flowerShape: 'Spike-like',
    petalCount: 6 - 8,
    preferredpH: 7.0,
    seedType: 'Edible',
    historicalSignificance: 'Symbol of calmness, purity, and cleanliness',
  },
  {
    id: '39b028a5-3191-44b7-b16f-49f4cb73634f',
    name: 'Petunia',
    species: 'Petunia spp.',
    color: 'Purple',
    bloomTime: 'Spring to Fall',
    origin: 'South America',
    heightInCm: 40,
    widthInCm: 35,
    soilType: 'Well-drained, loamy',
    sunExposure: 'Full Sun',
    wateringFrequency: 'Moderate',
    temperatureTolerance: '15°C to 30°C',
    fragrance: true,
    floweringDuration: '8-10 weeks',
    foliageColor: 'Green',
    plantType: 'Annual',
    growthRate: 'Moderate',
    toxicity: false,
    use: ['Ornamental'],
    pests: ['Aphids', 'Whiteflies'],
    diseases: ['Powdery Mildew'],
    propagationMethods: ['Seeds'],
    pruningRequirements: 'Pinch back to encourage more blooms',
    plantHardinessZone: '9-11',
    companionPlants: ['Geraniums', 'Marigolds'],
    maintenanceLevel: 'Medium',
    flowerShape: 'Funnel-shaped',
    petalCount: 5 - 7,
    preferredpH: 6.0,
    seedType: 'Non-edible',
    historicalSignificance: 'Symbol of love and desire',
  },
  {
    id: 'a99f2234-e11b-4e1c-a8b7-01bfb8304f8a',
    name: 'Chrysanthemum',
    species: 'Chrysanthemum morifolium',
    color: 'Yellow',
    bloomTime: 'Fall',
    origin: 'Asia',
    heightInCm: 90,
    widthInCm: 60,
    soilType: 'Well-drained, fertile',
    sunExposure: 'Full Sun',
    wateringFrequency: 'Moderate',
    temperatureTolerance: '10°C to 25°C',
    fragrance: true,
    floweringDuration: '4-6 weeks',
    foliageColor: 'Green',
    plantType: 'Perennial',
    growthRate: 'Moderate',
    toxicity: false,
    use: ['Ornamental'],
    pests: ['Aphids', 'Spider Mites'],
    diseases: ['Powdery Mildew'],
    propagationMethods: ['Cuttings', 'Division'],
    pruningRequirements: 'Deadhead to prolong blooming',
    plantHardinessZone: '5-9',
    companionPlants: ['Marigolds', 'Kale'],
    maintenanceLevel: 'Medium',
    flowerShape: 'Pompon-shaped',
    petalCount: 20 - 30,
    preferredpH: 6.5,
    seedType: 'Non-edible',
    historicalSignificance: 'Symbol of longevity and prosperity',
  },
];

export default FlowerData;
